//                                                                     ⨯  ROW
const char dramRU5[] = { CMD_INIT_16_3|FL_DRAM, b11111111, b11011111, 0, 0x08 };
const char dramRU6[] = { CMD_INIT_16_3|FL_DRAM, b11111111, b11011111, 0, 0x07 };
const char dramRU7[] = { CMD_INIT_16_3|FL_DRAM, b11111111, b11011111, 0, 0x09 };
const char dramRU9[] = { CMD_INIT_18_1|FL_DRAM, b11111111, b11111111, b00000010, 1, 0x0A };
