#define tlenAP    9
#define tlenIV    2
#define tlenID    7
#define tlenIE    16
#define tlenIM    3
#define tlenIP    5
#define tlenIR    21
#define tlenKP    12
#define tlenLA    20
#define tlenLE    9
#define tlenLI    9
#define tlenLL    3
#define tlenLN    8
#define tlenLP    9
#define tlenLR    7
#define tlenPR    2
#define tlenRP    2
#define tlenRU    2
#define tlenSP    2
#define tlenTV    7
#define tlenTL    4
#define tlenTM    6
#define tlenTR    2
#define tlenTTL    24
const char * const tlabAP[] = { 0,tlab005D,tlab005E,tlab005F,tlab0074,tlab0075,tlab001C,tlab001D,tlab0001 };
const char * const tlabIV[] = { 0,tlab0033 };
const char * const tlabID[] = { 0,tlab0024,tlab0048,tlab0035,tlab0049,tlab0036,tlab0017 };
const char * const tlabIE[] = { 0,tlab002D,tlab0057,tlab0053,tlab0054,tlab0055,tlab0056,tlab0062,tlab0063,tlab0003,tlab0067,tlab000C,tlab000D,tlab0064,tlab0065,tlab0011 };
const char * const tlabIM[] = { 0,tlab002F,tlab0020 };
const char * const tlabIP[] = { 0,tlab001E,tlab0000,tlab000F,tlab0076 };
const char * const tlabIR[] = { 0,tlab0010,tlab0016,tlab006D,tlab0077,tlab0004,tlab0013,tlab0060,tlab0002,tlab006A,tlab0051,tlab0014,tlab006F,tlab0025,tlab000B,tlab006E,tlab006B,tlab0061,tlab0026,tlab0066,tlab006C };
const char * const tlabKP[] = { 0,tlab0058,tlab0034,tlab005C,tlab0059,tlab0068,tlab005A,tlab0069,tlab005B,tlab0018,tlab0070,tlab0071 };
const char * const tlabLA[] = { 0,tlab003E,tlab003A,tlab003B,tlab0040,tlab003E,tlab003F,tlab003D,tlab003C,tlab0041,tlab003C,tlab003B,tlab003C,tlab003E,tlab0006,tlab0042,tlab003B,tlab003E,tlab003B,tlab0040 };
const char * const tlabLE[] = { 0,tlab0043,tlab002B,tlab002A,tlab0030,tlab0043,tlab0043,tlab0043,tlab0044 };
const char * const tlabLI[] = { 0,tlab0046,tlab0047,tlab0028,tlab0027,tlab0005,tlab0032,tlab0046,tlab0028 };
const char * const tlabLL[] = { 0,tlab0045,tlab0045 };
const char * const tlabLN[] = { 0,tlab0038,tlab0039,tlab0039,tlab0039,tlab002C,tlab0038,tlab0039 };
const char * const tlabLP[] = { 0,tlab0072,tlab002E,tlab0031,tlab004C,tlab0050,tlab0073,tlab004D,tlab004C };
const char * const tlabLR[] = { 0,tlab0022,tlab0037,tlab001F,tlab0008,tlab0023,tlab0019 };
const char * const tlabPR[] = { 0,tlab000E };
const char * const tlabRP[] = { 0,tlab006E };
const char * const tlabRU[] = { 0,tlab0015 };
const char * const tlabSP[] = { 0,tlab0021 };
const char * const tlabTV[] = { 0,tlab001A,tlab001B,tlab0052,tlab0007,tlab0009,tlab000A };
const char * const tlabTL[] = { 0,tlab003E,tlab0038,tlab003B };
const char * const tlabTM[] = { 0,tlab004A,tlab004B,tlab0029,tlab004E,tlab004F };
const char * const tlabTR[] = { 0,tlab0012 };
const char * const titemAP[] = { "#$","¿œ3","¿œ4","¿œ5","¿œ6","¿œ9","¿œ14","¿œ15","¿œ16" };
const char * const titemIV[] = { "#$","»¬1" };
const char * const titemID[] = { "#$","»ƒ3","»ƒ4","»ƒ6","»ƒ7","»ƒ10","»ƒ14" };
const char * const titemIE[] = { "#$","»≈1","»≈2","»≈4","»≈5","»≈6","»≈7","»≈9","»≈10","»≈12","»≈13","»≈16","»≈17","»≈18","»≈19","»≈23" };
const char * const titemIM[] = { "#$","»Ã2","»Ã3" };
const char * const titemIP[] = { "#$","»œ2","»œ3","»œ5","»œ7" };
const char * const titemIR[] = { "#$","»–1","»–8","»–9","»–10","»–13","»–15","»–16","»–17","»–22","»–23","»–24","»–26","»–27","»–30","»–32","»–33","»–34","»–35","»–37","»–38" };
const char * const titemKP[] = { "#$"," œ2"," œ5"," œ7"," œ11"," œ12"," œ13"," œ14"," œ15"," œ16"," œ17"," œ19" };
const char * const titemLA[] = { "#$","À¿1","À¿2","À¿3","À¿4","À¿6","À¿7","À¿8","À¿9","À¿10","À¿11","À¿12","À¿13","À¿16","À¿17","À¿18","À¿21","À¿22","À¿23","À¿24" };
const char * const titemLE[] = { "#$","À≈1","À≈2","À≈3","À≈4","À≈5","À≈6","À≈10","À≈11" };
const char * const titemLI[] = { "#$","À»1","À»2","À»3","À»4","À»5","À»6","À»8","À»10" };
const char * const titemLL[] = { "#$","ÀÀ1","ÀÀ4" };
const char * const titemLN[] = { "#$","ÀÕ1","ÀÕ2","ÀÕ3","ÀÕ5","ÀÕ7","ÀÕ8","ÀÕ10" };
const char * const titemLP[] = { "#$","Àœ5","Àœ7","Àœ8","Àœ9","Àœ11","Àœ12","Àœ16","Àœ17" };
const char * const titemLR[] = { "#$","À–1","À–3","À–4","À–9","À–11","À–13" };
const char * const titemPR[] = { "#$","œ–6" };
const char * const titemRP[] = { "#$","–œ1" };
const char * const titemRU[] = { "#$","–”2" };
const char * const titemSP[] = { "#$","—œ1" };
const char * const titemTV[] = { "#$","“¬1","“¬6","“¬9","“¬10","“¬11","“¬15" };
const char * const titemTL[] = { "#$","“À1","“À2","“À3" };
const char * const titemTM[] = { "#$","“Ã2","“Ã5","“Ã7","“Ã8","“Ã9" };
const char * const titemTR[] = { "#$","“–2" };
const MENU tmnuAP = { titemAP, 0x80, tlenAP, (MENU **) tlabAP };
const MENU tmnuIV = { titemIV, 0x80, tlenIV, (MENU **) tlabIV };
const MENU tmnuID = { titemID, 0x80, tlenID, (MENU **) tlabID };
const MENU tmnuIE = { titemIE, 0x80, tlenIE, (MENU **) tlabIE };
const MENU tmnuIM = { titemIM, 0x80, tlenIM, (MENU **) tlabIM };
const MENU tmnuIP = { titemIP, 0x80, tlenIP, (MENU **) tlabIP };
const MENU tmnuIR = { titemIR, 0x80, tlenIR, (MENU **) tlabIR };
const MENU tmnuKP = { titemKP, 0x80, tlenKP, (MENU **) tlabKP };
const MENU tmnuLA = { titemLA, 0x80, tlenLA, (MENU **) tlabLA };
const MENU tmnuLE = { titemLE, 0x80, tlenLE, (MENU **) tlabLE };
const MENU tmnuLI = { titemLI, 0x80, tlenLI, (MENU **) tlabLI };
const MENU tmnuLL = { titemLL, 0x80, tlenLL, (MENU **) tlabLL };
const MENU tmnuLN = { titemLN, 0x80, tlenLN, (MENU **) tlabLN };
const MENU tmnuLP = { titemLP, 0x80, tlenLP, (MENU **) tlabLP };
const MENU tmnuLR = { titemLR, 0x80, tlenLR, (MENU **) tlabLR };
const MENU tmnuPR = { titemPR, 0x80, tlenPR, (MENU **) tlabPR };
const MENU tmnuRP = { titemRP, 0x80, tlenRP, (MENU **) tlabRP };
const MENU tmnuRU = { titemRU, 0x80, tlenRU, (MENU **) tlabRU };
const MENU tmnuSP = { titemSP, 0x80, tlenSP, (MENU **) tlabSP };
const MENU tmnuTV = { titemTV, 0x80, tlenTV, (MENU **) tlabTV };
const MENU tmnuTL = { titemTL, 0x80, tlenTL, (MENU **) tlabTL };
const MENU tmnuTM = { titemTM, 0x80, tlenTM, (MENU **) tlabTM };
const MENU tmnuTR = { titemTR, 0x80, tlenTR, (MENU **) tlabTR };
const char * const titemTTL[] = { "#$","¿œ","»¬","»ƒ","»≈","»Ã","»œ","»–"," œ","À¿","À≈","À»","ÀÀ","ÀÕ","Àœ","À–","œ–","–œ","–”","—œ","“¬","“À","“Ã","“–"};
const MENU * const tlabTTL[] = { 0,&tmnuAP,&tmnuIV,&tmnuID,&tmnuIE,&tmnuIM,&tmnuIP,&tmnuIR,&tmnuKP,&tmnuLA,&tmnuLE,&tmnuLI,&tmnuLL,&tmnuLN,&tmnuLP,&tmnuLR,&tmnuPR,&tmnuRP,&tmnuRU,&tmnuSP,&tmnuTV,&tmnuTL,&tmnuTM,&tmnuTR};
const MENU mnuTTL = { titemTTL, 0, tlenTTL, tlabTTL  };
